language: go
sudo: false
notifications:
  email: false

env:
  global:
    - PROJECT_NAME=goscrape
    - PROJECT_REPO=cornelk/goscrape
    - VERSION="${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID}"
    - GO111MODULE=on
    - GOFLAGS="-mod=readonly"

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

matrix:
  include:
    - go: 1.13.x
      env: LATEST=true
    - go: tip
  allow_failures:
    - go: tip

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - export BINARY_PREFIX=${PROJECT_NAME}-${VERSION}
  - export BINARY_NAME=${BINARY_PREFIX}-windows-amd64.exe
  - GOOS=windows GOARCH=amd64 go build -o ${BINARY_NAME}
  - shasum -a 256 "${BINARY_NAME}" > "${BINARY_NAME}.sha256"
  - export BINARY_NAME=${BINARY_PREFIX}-linux-amd64
  - GOOS=linux GOARCH=amd64 go build -o ${BINARY_NAME}
  - shasum -a 256 "${BINARY_NAME}" > "${BINARY_NAME}.sha256"
  - export BINARY_NAME=${BINARY_PREFIX}-darwin-amd64
  - GOOS=darwin GOARCH=amd64 go build -o ${BINARY_NAME}
  - shasum -a 256 "${BINARY_NAME}" > "${BINARY_NAME}.sha256"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "h+xBXIsfq54v4dylcyqHtWbSRHuMd6qzhM5FsLsDrHdKIj8j50k4Lb9ofBXBbYR9y0nmWC3bdFHGyKVzbWXniyDJTSUzvWP5GwfVRt2xalAcEUctHUFpOXSiEpB3UJSphgoSu1FG07MluyK6f2Sr/9ijFeZxZfr2i/GndV6rjbF6m3Virm15hnK0W7zIkgGFwqFHhTZAOh9+ArX55ZGa8lL6VyG1YKt3WNCxndGUw0uspzRlGfPQknd4t4kt8R7KsNyjXEnXZf2BSjJj4uS0HxLY0vP2zpTlzWFc5w/9JpR+1fFq2tL6OK3sLzoxnvAy+W66W1bTI03ZZLLgBSOKgc0jp3hebcYKPLpebmp/C/Tm6ZxiB0fKGRq6VkCb6+96qQVWjsrxUtEUNLQo6GLq8x8zJ21iVaV3AGLuq2q3fbHJilmAfvnSROlaGx1Ds++ChhP7FjV2tDkVQGpWDjZGUO1DI63id21W6OXEVGEWz5sbVqoDyOtoLCtiHR4JXo9XzHOsdNcu5iAs3XC1bdPeVCG0wwTAbrYEMiS/4dH/RqXtUS4gXSxD9l1ThMiYf4hj6LXCwXXPi6/9n07IrhvNSWwPyLoWMFc8GIfTVZ6Ec9sYv25uMr/EzErNj5w0IxcQrn9jpgEr3NsNLClRqkPx3pm/VItb+4prf2n7lJ4gjl8="
  file:
    - ${BINARY_PREFIX}-windows-amd64.exe
    - ${BINARY_PREFIX}-windows-amd64.exe.sha256
    - ${BINARY_PREFIX}-linux-amd64
    - ${BINARY_PREFIX}-linux-amd64.sha256
    - ${BINARY_PREFIX}-darwin-amd64
    - ${BINARY_PREFIX}-darwin-amd64.sha256
  on:
    condition: ${LATEST} = true
    repo: ${PROJECT_REPO}
    branch: master
    tags: true
